log-mask.logging.rest-template.name-value-shape=COMPACT
log-mask.governance.http.path.rules[0].pattern=/samples/customers/{customerId}
log-mask.governance.http.path.rules[0].variables[0].name=customerId
log-mask.governance.http.path.rules[0].variables[0].type=REDACT
log-mask.governance.http.query.rules[0].name=token
log-mask.governance.http.query.rules[0].type=REDACT
log-mask.governance.http.headers.request.rules[0].name=X-Secret
log-mask.governance.http.headers.request.rules[0].type=REDACT
log-mask.governance.http.headers.response.rules[0].name=X-Response-Secret
log-mask.governance.http.headers.response.rules[0].type=REDACT
